import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Client from "@/components/Client";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/context/AuthProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-bl from-gray-200 to-gray-300`}
      >
        <AuthProvider>
            <Toaster/>
            <NavBar/>
            <Client>
                {children}
            </Client>
            <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
